from pathlib import Path
from typing import List


class OutputManager:
    """
    Manages the output files generated by EnergyPlus (CSV, SQL, ESO, ERR, MTR).
    """

    def __init__(self, output_directory: str):
        self.output_directory = Path(output_directory)

    def prepare_directory(self) -> None:
        """
        Ensures the output directory exists and is clean if necessary.
        """
        if not self.output_directory.exists():
            self.output_directory.mkdir(parents=True, exist_ok=True)

    def get_eplus_args(self) -> List[str]:
        """
        Returns the command line arguments required by the EnergyPlus API
        to direct outputs to the configured directory.
        """
        return ["-d", str(self.output_directory.absolute())]
