"use client"

import * as React from "react"
import { ArrowRight, Clock3, Layers3, PlayCircle, Target } from "lucide-react"
import { useMutation, useQueryClient } from "@tanstack/react-query"

import { backend } from "@/services/backend"
import { useDecisionGoalsQuery } from "@/hooks/use-backend-queries"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import type { ExecutionPlan } from "@/types/api"

export default function DecisionsPage() {
  const goals = useDecisionGoalsQuery()
  const queryClient = useQueryClient()
  const [selectedGoalId, setSelectedGoalId] = React.useState<string | null>(null)
  const [plan, setPlan] = React.useState<ExecutionPlan | null>(null)
  const goalList = (goals.data ?? []) as Array<{ id: string; goal_type: string; priority: number; building_id: string }>

  const buildPlan = useMutation({
    mutationFn: (goalId: string) => backend.decision.goalPlan(goalId),
    onSuccess: async (result) => {
      setPlan(result)
      await queryClient.invalidateQueries({ queryKey: ["backend", "decision", "goals"] })
    },
  })

  const selectedGoal = goalList.find((goal) => goal.id === selectedGoalId) ?? goalList[0] ?? null

  React.useEffect(() => {
    if (!selectedGoalId && goalList.length) {
      setSelectedGoalId(goalList[0].id)
    }
  }, [goalList, selectedGoalId])

  return (
    <div className="grid gap-4 xl:grid-cols-[1fr_0.95fr]">
      <Card className="border-border/60 bg-background/70 backdrop-blur-xl">
        <CardHeader>
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <div className="text-sm uppercase tracking-[0.22em] text-muted-foreground">Decision center</div>
              <CardTitle className="text-3xl">Decision Goals</CardTitle>
              <CardDescription>Backend-managed goals and execution plans generated by the AI planner and decision engine.</CardDescription>
            </div>
            <Badge variant="secondary" className="rounded-full px-3 py-1">{goals.data?.length ?? 0} goals</Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-3">
          {goalList.map((goal) => (
            <button
              key={goal.id}
              onClick={() => setSelectedGoalId(goal.id)}
              className={`w-full rounded-2xl border p-4 text-left transition ${selectedGoal?.id === goal.id ? "border-foreground bg-foreground text-background" : "border-border/60 bg-muted/30 hover:bg-muted/50"}`}
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <div className="font-medium">{goal.goal_type}</div>
                  <div className={`text-sm ${selectedGoal?.id === goal.id ? "text-background/80" : "text-muted-foreground"}`}>Building {goal.building_id}</div>
                </div>
                <Badge variant="outline" className={`rounded-full ${selectedGoal?.id === goal.id ? "border-background/20 text-background" : ""}`}>Priority {goal.priority}</Badge>
              </div>
            </button>
          ))}
          {!goals.data?.length && <div className="rounded-2xl border border-dashed border-border/60 p-10 text-center text-muted-foreground">No decision goals yet. Use the AI Copilot or decision API.</div>}
        </CardContent>
      </Card>

      <div className="space-y-4">
        <Card className="border-border/60 bg-background/70 backdrop-blur-xl">
          <CardHeader>
            <CardTitle>Execution Plan</CardTitle>
            <CardDescription>Generated plan with simulation jobs and ordered execution steps.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-3 md:grid-cols-2">
              <div className="rounded-2xl border border-border/60 bg-muted/40 p-4"><div className="text-sm text-muted-foreground">Goal</div><div className="mt-1 font-medium">{selectedGoal?.goal_type ?? "Select a goal"}</div></div>
              <div className="rounded-2xl border border-border/60 bg-muted/40 p-4"><div className="text-sm text-muted-foreground">Runtime</div><div className="mt-1 font-medium">{plan?.estimated_runtime ?? 0} min</div></div>
              <div className="rounded-2xl border border-border/60 bg-muted/40 p-4"><div className="text-sm text-muted-foreground">Status</div><div className="mt-1 font-medium">{plan?.status ?? "CREATED"}</div></div>
              <div className="rounded-2xl border border-border/60 bg-muted/40 p-4"><div className="text-sm text-muted-foreground">Execution order</div><div className="mt-1 font-medium">{plan?.execution_order.length ?? 0} steps</div></div>
            </div>
            <Button className="rounded-full" onClick={() => selectedGoal && buildPlan.mutate(selectedGoal.id)} disabled={!selectedGoal || buildPlan.isPending}><PlayCircle className="mr-2 size-4" /> Build execution plan</Button>
            <div className="space-y-3 rounded-2xl border border-border/60 bg-background/80 p-4">
              {(plan?.execution_order ?? ["Validate goal", "Queue simulation", "Review output", "Apply recommendation"]).map((step, index) => (
                <div key={step} className="flex items-center gap-3 text-sm">
                  <div className="flex size-8 items-center justify-center rounded-full bg-foreground text-background">{index + 1}</div>
                  <div className="font-medium">{step}</div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card className="border-border/60 bg-background/70 backdrop-blur-xl">
          <CardHeader>
            <CardTitle>Simulation Jobs</CardTitle>
            <CardDescription>Jobs extracted from the current execution plan.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            {(plan?.simulation_jobs ?? ["sim-001", "sim-002", "sim-003"]).map((job) => (
              <div key={job} className="flex items-center justify-between rounded-2xl border border-border/60 bg-muted/40 px-4 py-3">
                <span>{job}</span>
                <ArrowRight className="size-4 text-muted-foreground" />
              </div>
            ))}
          </CardContent>
        </Card>

        <Card className="border-border/60 bg-background/70 backdrop-blur-xl">
          <CardHeader>
            <CardTitle>Timeline</CardTitle>
            <CardDescription>High-level chronology for decision lifecycle execution.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 text-sm">
            {[
              { label: "Goal validated", meta: "Target and constraints accepted" },
              { label: "Plan generated", meta: "Simulation jobs ordered" },
              { label: "Runtime estimated", meta: "Resource and duration synthesis" },
              { label: "Recommendation delivered", meta: "Ready for operator review" },
            ].map((item, index) => (
              <div key={item.label} className="flex gap-3">
                <div className="flex flex-col items-center">
                  <div className="size-3 rounded-full bg-foreground" />
                  {index < 3 && <div className="h-10 w-px bg-border" />}
                </div>
                <div className="space-y-1 pb-4">
                  <div className="font-medium">{item.label}</div>
                  <div className="text-muted-foreground">{item.meta}</div>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
